/**
 * generators/c_fsm.js
 * Machine Studio [MS] — C generator for the FSM formalism.
 *
 * Emits a classic finite-state machine: a single current state, a
 * transition table keyed by (state, trigger), and a per-state entry
 * hook. This is deliberately NOT the Petri token engine in c_lang.js —
 * when the user is in FSM mode we generate the simpler, idiomatic FSM
 * they expect.
 *
 * Patterns:
 *   'table'  — static transition array + linear dispatch.
 *   'switch' — nested switch (state → trigger).
 * Both expose the same public API in state_machine.h:
 *   sm_init / sm_reset / sm_current_state / sm_state_name /
 *   sm_is_final / sm_fire(id) / fire_<trigger>()
 *
 * Files: state_machine.h, state_machine.c, main.c,
 *        test_state_machine.c (Unity), Makefile, README.md
 *
 * c_lang.generate() delegates here when ir.mode === 'FSM'.
 *
 * Depends on: emit.js, gen_tests.js (IR shape from walker.js)
 */

const c_fsm = (() => {

    const SUPPORTED_PATTERNS = ['table', 'switch'];

    function generate(ir, opts) {
        if (ir.states.length === 0) {
            return { ok: false, error: 'Machine has no states — nothing to generate.' };
        }
        const pattern = SUPPORTED_PATTERNS.includes(opts.pattern) ? opts.pattern : 'table';
        const ctx = _ctx(ir);

        const files = [
            { name: 'state_machine.h', content: _emitHeader(ctx) },
            { name: 'state_machine.c', content: _emitSource(ctx, pattern) },
            { name: 'main.c',          content: _emitMain(ctx) },
            { name: 'test_state_machine.c', content: _emitTests(ctx) },
            { name: 'Makefile',        content: _emitMakefile(ctx) },
            { name: 'README.md',       content: _emitReadme(ctx, pattern) }
        ];
        return { ok: true, files, previewFile: 'state_machine.c', warnings: ir.warnings || [] };
    }

    /* ── context ──────────────────────────────────────────────────── */

    function _ctx(ir) {
        const start = ir.states.find(s => s.kind === 'start') || ir.states[0];
        const finals = ir.states.filter(s => s.kind === 'end');
        // Only triggered transitions can fire in an FSM.
        const fireable = ir.transitions.filter(t => t.trigger);
        const dropped  = ir.transitions.length - fireable.length;
        return {
            ir, start, finals, fireable, dropped,
            stamp: new Date().toISOString().slice(0, 10)
        };
    }

    /* ── header ───────────────────────────────────────────────────── */

    function _emitHeader(ctx) {
        const ir = ctx.ir;

        const stateEnum = ir.states
            .map(s => '    ' + emit.pad(s.enumName + ',', 28) + '/* ' + s.name + ' */')
            .join('\n');

        const triggerConsts = ir.triggers.length
            ? ir.triggers.map((t, i) =>
                '#define ' + emit.pad(t.constName, 28) + ' ' + i +
                '   /* ' + t.name + (t.kind === 'timer' ? ' (timer)' : '') + ' */'
              ).join('\n')
            : '/* No triggers defined — sm_fire() is always a no-op. */';

        const entryExterns = ir.states
            .map(s => 'extern void ' + s.handlerName + '(void);   /* on entering ' + s.name + ' */')
            .join('\n');

        const triggerFnDecls = ir.triggers.length
            ? ir.triggers.map(t => 'int ' + t.fnName + '(void);').join('\n')
            : '/* No per-trigger helpers: no triggers were defined. */';

        const body =
`#include <stddef.h>

/* ── States ─────────────────────────────────────────────────────── */
typedef enum {
${stateEnum}
    SM_STATE_COUNT
} sm_state_t;

/* ── Trigger ids ────────────────────────────────────────────────── */
${triggerConsts}

/* ── Per-state entry hooks ──────────────────────────────────────────
   Called once each time the machine ENTERS the state (including the
   initial sm_init). Implement these in your own .c file. */
${entryExterns}

/* ── Public API ─────────────────────────────────────────────────── */
void        sm_init(void);              /* enter the start state */
void        sm_reset(void);             /* alias for sm_init */
sm_state_t  sm_current_state(void);     /* the single active state */
const char* sm_state_name(sm_state_t s);
int         sm_is_final(void);          /* 1 if the current state is an end state */

/* Fire a trigger by id. Returns 1 if a transition fired, 0 if the
   trigger is not wired out of the current state (a harmless no-op). */
int         sm_fire(int trigger_id);

/* Per-trigger helpers — each forwards to sm_fire(). */
${triggerFnDecls}`;

        return emit.banner('state_machine.h  —  ' + ir.name, [
            'Finite-state machine (FSM) — generated by Machine Studio.',
            'Exactly one state is active at a time; sm_fire() moves it.',
            'Generated ' + ctx.stamp + '.'
        ]) + '\n' +
        emit.headerGuard('STATE_MACHINE_H', body);
    }

    /* ── source ───────────────────────────────────────────────────── */

    function _emitSource(ctx, pattern) {
        const ir = ctx.ir;

        const names = ir.states
            .map(s => '    ' + emit.pad('"' + _esc(s.name) + '",', 30) + '/* ' + s.enumName + ' */')
            .join('\n');

        const enterCases = ir.states
            .map(s => '        case ' + s.enumName + ': ' + s.handlerName + '(); break;')
            .join('\n');

        const finalCases = ctx.finals.length
            ? ctx.finals.map(s => '        case ' + s.enumName + ': return 1;').join('\n')
            : '        /* no end states defined */';

        const dispatch = pattern === 'switch'
            ? _emitSwitchDispatch(ctx)
            : _emitTableDispatch(ctx);

        const triggerFns = ir.triggers.length
            ? ir.triggers.map(t =>
                'int ' + emit.pad(t.fnName + '(void)', 30) + ' { return sm_fire(' + t.constName + '); }'
              ).join('\n')
            : '/* No per-trigger helpers. */';

        return emit.banner('state_machine.c  —  ' + ir.name, [
            'FSM implementation (' + pattern + ' dispatch). Generated by Machine Studio.',
            'Generated ' + ctx.stamp + '.'
        ]) + '\n\n' +
`#include "state_machine.h"

static const char* const SM_STATE_NAMES[SM_STATE_COUNT] = {
${names}
};

static const sm_state_t SM_START_STATE = ${ctx.start.enumName};

static sm_state_t g_state;

/* Call the entry hook for a state. */
static void sm_enter(sm_state_t s) {
    switch (s) {
${enterCases}
        default: break;
    }
}

void sm_init(void)  { g_state = SM_START_STATE; sm_enter(g_state); }
void sm_reset(void) { sm_init(); }

sm_state_t sm_current_state(void) { return g_state; }

const char* sm_state_name(sm_state_t s) {
    return (s >= 0 && s < SM_STATE_COUNT) ? SM_STATE_NAMES[s] : "(invalid)";
}

int sm_is_final(void) {
    switch (g_state) {
${finalCases}
        default: return 0;
    }
}

${dispatch}

${triggerFns}
`;
    }

    function _emitTableDispatch(ctx) {
        const rows = ctx.fireable.length
            ? ctx.fireable.map(t =>
                '    { ' + emit.pad(t.from.enumName + ',', 24) +
                emit.pad(t.trigger.constName + ',', 24) + t.to.enumName + ' },' +
                '   /* ' + t.from.name + ' --' + t.trigger.name + '--> ' + t.to.name + ' */'
              ).join('\n')
            : '    /* no triggered transitions */';

        return `/* ── Transition table ───────────────────────────────────────────── */
typedef struct { sm_state_t from; int trigger; sm_state_t to; } sm_transition_t;

static const sm_transition_t SM_TRANSITIONS[] = {
${rows}
};
static const int SM_TRANSITION_COUNT =
    (int)(sizeof(SM_TRANSITIONS) / sizeof(SM_TRANSITIONS[0]));

int sm_fire(int trigger_id) {
    int i;
    for (i = 0; i < SM_TRANSITION_COUNT; i++) {
        if (SM_TRANSITIONS[i].from == g_state &&
            SM_TRANSITIONS[i].trigger == trigger_id) {
            g_state = SM_TRANSITIONS[i].to;
            sm_enter(g_state);
            return 1;
        }
    }
    return 0;   /* trigger not valid from the current state */
}`;
    }

    function _emitSwitchDispatch(ctx) {
        // Group fireable transitions by source state.
        const byFrom = new Map();
        ctx.fireable.forEach(t => {
            if (!byFrom.has(t.from.enumName)) byFrom.set(t.from.enumName, []);
            byFrom.get(t.from.enumName).push(t);
        });

        let cases = '';
        byFrom.forEach((list, fromEnum) => {
            const inner = list.map(t =>
                '            case ' + t.trigger.constName + ': g_state = ' + t.to.enumName +
                '; sm_enter(g_state); return 1;   /* → ' + t.to.name + ' */'
            ).join('\n');
            cases +=
`        case ${fromEnum}:
            switch (trigger_id) {
${inner}
                default: break;
            }
            break;
`;
        });
        if (!cases) cases = '        /* no triggered transitions */\n';

        return `int sm_fire(int trigger_id) {
    switch (g_state) {
${cases}        default: break;
    }
    return 0;   /* trigger not valid from the current state */
}`;
    }

    /* ── demo main ────────────────────────────────────────────────── */

    function _emitMain(ctx) {
        const ir = ctx.ir;

        const handlerDefs = ir.states.map(s =>
            'void ' + s.handlerName + '(void) { printf("  entered %s\\n", "' + _esc(s.name) + '"); }'
        ).join('\n');

        const fireSeq = ir.triggers.length
            ? ir.triggers.map(t =>
`    printf("fire %-14s : ", "${_esc(t.name)}");
    ${t.fnName}();
    printf("now in %s\\n", sm_state_name(sm_current_state()));`
              ).join('\n')
            : '    printf("(no triggers to fire)\\n");';

        return emit.banner('main.c  —  ' + ir.name + ' demo', [
            'Runnable smoke demo with printing entry handlers.',
            'Build: make demo   (or see README.md). Generated ' + ctx.stamp + '.'
        ]) + '\n\n' +
`#include "state_machine.h"
#include <stdio.h>

/* Demo entry handlers (replace with your own logic). */
${handlerDefs}

int main(void) {
    sm_init();
    printf("start state: %s\\n", sm_state_name(sm_current_state()));
    printf("---- firing every trigger once ----\\n");
${fireSeq}
    printf("final? %s\\n", sm_is_final() ? "yes" : "no");
    return 0;
}
`;
    }

    /* ── Unity tests ──────────────────────────────────────────────── */

    function _emitTests(ctx) {
        const ir = ctx.ir;
        const cases = [];

        cases.push({
            name: 'test_starts_in_start_state',
            body: 'TEST_ASSERT_EQUAL_INT(' + ctx.start.enumName + ', sm_current_state());'
        });

        // First triggered transition out of the start state → deterministic move.
        const fromStart = ctx.fireable.find(t => t.from.enumName === ctx.start.enumName);
        if (fromStart) {
            cases.push({
                name: 'test_fire_from_start_moves_state',
                body:
`int moved = sm_fire(${fromStart.trigger.constName});
TEST_ASSERT_EQUAL_INT(1, moved);   /* a transition fired */
TEST_ASSERT_EQUAL_INT(${fromStart.to.enumName}, sm_current_state());`
            });
        }

        cases.push({
            name: 'test_unknown_trigger_is_ignored',
            body:
`int moved = sm_fire(9999);   /* not a real trigger id */
TEST_ASSERT_EQUAL_INT(0, moved);
TEST_ASSERT_EQUAL_INT(${ctx.start.enumName}, sm_current_state());   /* unchanged */`
        });

        // TODO scaffold so the user sees where to extend.
        cases.push({
            name: 'test_TODO_add_your_own',
            body:
`/* Drive the machine through a scenario and assert the resulting state.
   Example:
       sm_fire(TRIG_SOMETHING);
       sm_fire(TRIG_SOMETHING_ELSE);
       TEST_ASSERT_EQUAL_INT(S_EXPECTED, sm_current_state()); */
TEST_ASSERT_TRUE(1);`
        });

        return gen_tests.unity({
            title: ir.name,
            header: 'state_machine.h',
            stubs: ir.states.map(s => s.handlerName),
            cases
        });
    }

    /* ── Makefile ─────────────────────────────────────────────────── */

    function _emitMakefile(ctx) {
        return `# Makefile — ${ctx.ir.name} (FSM)
# Generated by Machine Studio ${ctx.stamp}.

CC      ?= cc
CFLAGS  ?= -std=c11 -Wall -Wextra -O2

SRC      = state_machine.c
DEMO     = main.c
TESTSRC  = test_state_machine.c

# Unity lives wherever you put it. Point UNITY_DIR at the folder that
# holds unity.c / unity.h (e.g. a Unity checkout's src/), or drop those
# files next to this Makefile (the default '.').
UNITY_DIR ?= .
UNITY_SRC  = $(UNITY_DIR)/unity.c

all: demo

demo: $(SRC) $(DEMO)
	$(CC) $(CFLAGS) -o demo $(SRC) $(DEMO)

# Build + run the Unity test suite.
test: $(SRC) $(TESTSRC) $(UNITY_SRC)
	$(CC) $(CFLAGS) -I$(UNITY_DIR) -o run_tests $(SRC) $(TESTSRC) $(UNITY_SRC)
	./run_tests

clean:
	rm -f demo run_tests

.PHONY: all test clean
`;
    }

    /* ── README ───────────────────────────────────────────────────── */

    function _emitReadme(ctx, pattern) {
        const ir = ctx.ir;
        const triggerList = ir.triggers.length
            ? ir.triggers.map(t => '- `' + t.constName + '` / `' + t.fnName + '()` — ' + t.name +
                                    (t.kind === 'timer' ? ' _(timer in the editor)_' : '')).join('\n')
            : '_None._';
        const droppedNote = ctx.dropped > 0
            ? '\n> ⚠️ ' + ctx.dropped + ' transition(s) without a trigger were omitted — ' +
              'an FSM transition needs a trigger to fire.\n'
            : '';

        return `# ${ir.name} — Finite-State Machine (C)

Generated by **Machine Studio** ${ctx.stamp} · \`${pattern}\` dispatch.

Exactly one state is active at a time. \`sm_fire(trigger_id)\` looks up the
transition for *(current state, trigger)* and, if one exists, moves to the
target state and calls its entry hook. Unknown triggers are ignored.
${droppedNote}
## API (\`state_machine.h\`)

| Function | Purpose |
|---|---|
| \`sm_init()\` / \`sm_reset()\` | Enter the start state (\`${ctx.start.enumName}\`). |
| \`sm_current_state()\` | The active \`sm_state_t\`. |
| \`sm_state_name(s)\` | Human-readable name. |
| \`sm_is_final()\` | 1 if the current state is an end state. |
| \`sm_fire(id)\` | Fire a trigger; returns 1 if it moved, 0 if ignored. |
| \`fire_<name>()\` | Per-trigger convenience wrappers. |

You implement the per-state entry hooks (\`extern void state_*(void)\`); they
fire whenever the machine enters that state.

### Triggers
${triggerList}

## Build & run

\`\`\`sh
make demo      # builds ./demo from state_machine.c + main.c
./demo
\`\`\`

## Tests (Unity)

\`test_state_machine.c\` is a [Unity](https://github.com/ThrowTheSwitch/Unity)
template. Put \`unity.c\` / \`unity.h\` beside these files (or set \`UNITY_DIR\`),
then:

\`\`\`sh
make test      # compiles state_machine.c + test_state_machine.c + unity.c
\`\`\`

The generated cases cover the start state, the first transition out of it,
and that unknown triggers are ignored — extend with your own scenarios.
`;
    }

    /* ── util ─────────────────────────────────────────────────────── */
    function _esc(s) { return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"'); }

    return { generate, SUPPORTED_PATTERNS };
})();

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { c_fsm };
}
