/**
 * generators/cpp_fsm.js
 * Machine Studio [MS] — C++ generator for the FSM formalism.
 *
 * Emits a classic finite-state machine behind a single `StateMachine`
 * class: one current state, transitions keyed by (state, trigger), and
 * a virtual onEnter(State) entry hook. NOT the Petri engine in
 * cpp_lang.js — used when the user is in FSM mode.
 *
 * Patterns (all share the same class facade, so the test file is
 * pattern-independent — only the fire() dispatch differs):
 *   'table'  — static transition array + loop.
 *   'switch' — nested switch (state → trigger).
 *   'oop'    — per-state lambdas held in an array (object-flavoured).
 *
 * Files: state_machine.hpp, state_machine.cpp, main.cpp,
 *        test_state_machine.cpp (GoogleTest), Makefile, README.md
 *
 * cpp_lang.generate() delegates here when ir.mode === 'FSM'.
 *
 * Depends on: sanitize.js, emit.js, gen_tests.js (IR shape from walker.js)
 */

const cpp_fsm = (() => {

    const SUPPORTED_PATTERNS = ['table', 'switch', 'oop'];

    function generate(ir, opts) {
        if (ir.states.length === 0) {
            return { ok: false, error: 'Machine has no states — nothing to generate.' };
        }
        const pattern = SUPPORTED_PATTERNS.includes(opts.pattern) ? opts.pattern : 'table';
        const ctx = _ctx(ir);

        const files = [
            { name: 'state_machine.hpp', content: _emitHeader(ctx) },
            { name: 'state_machine.cpp', content: _emitSource(ctx, pattern) },
            { name: 'main.cpp',          content: _emitMain(ctx) },
            { name: 'test_state_machine.cpp', content: _emitTests(ctx) },
            { name: 'Makefile',          content: _emitMakefile(ctx) },
            { name: 'README.md',         content: _emitReadme(ctx, pattern) }
        ];
        return { ok: true, files, previewFile: 'state_machine.cpp', warnings: ir.warnings || [] };
    }

    /* ── context + C++ PascalCase names ───────────────────────────── */

    function _toPascal(words) {
        return words.filter(p => p.length > 0)
                    .map(p => p[0].toUpperCase() + p.slice(1).toLowerCase())
                    .join('');
    }

    function _ctx(ir) {
        const usedState   = new Set(['Count']);
        const usedTrigger = new Set();

        const states = ir.states.map(s => {
            let parts = s.enumName.split('_').filter(Boolean);
            if (parts[0] === 'S') parts.shift();
            const cppEnum = sanitize.disambiguate(_toPascal(parts) || ('State' + s.index), usedState);
            return Object.assign({}, s, { cppEnum });
        });
        const triggers = ir.triggers.map(t => {
            let parts = t.constName.split('_').filter(Boolean);
            if (parts[0] === 'TRIG') parts.shift();
            const cppEnum = sanitize.disambiguate(_toPascal(parts) || ('Trigger' + t.index), usedTrigger);
            return Object.assign({}, t, { cppEnum });
        });

        const sById = new Map(states.map(s => [s.id, s]));
        const tById = new Map(triggers.map(t => [t.id, t]));

        const fireable = ir.transitions
            .filter(t => t.trigger)
            .map(t => ({ from: sById.get(t.from.id), to: sById.get(t.to.id), trigger: tById.get(t.trigger.id) }))
            .filter(t => t.from && t.to && t.trigger);
        const dropped = ir.transitions.length - fireable.length;

        const start  = states.find(s => s.kind === 'start') || states[0];
        const finals = states.filter(s => s.kind === 'end');

        return { ir, states, triggers, fireable, dropped, start, finals,
                 stamp: new Date().toISOString().slice(0, 10) };
    }

    /* ── header ───────────────────────────────────────────────────── */

    function _emitHeader(ctx) {
        const stateEnum = ctx.states
            .map(s => '    ' + emit.pad(s.cppEnum + ',', 22) + '// ' + s.name)
            .join('\n');
        const trigEnum = ctx.triggers.length
            ? ctx.triggers.map(t => '    ' + emit.pad(t.cppEnum + ',', 22) + '// ' + t.name +
                                    (t.kind === 'timer' ? ' (timer)' : '')).join('\n')
            : '    // (no triggers defined)';
        const perTrigger = ctx.triggers.length
            ? ctx.triggers.map(t => '    bool ' + t.fnName + '();   // fire(Trigger::' + t.cppEnum + ')').join('\n')
            : '    // (no per-trigger helpers)';

        return emit.banner('state_machine.hpp  —  ' + ctx.ir.name, [
            'Finite-state machine (FSM) — generated by Machine Studio.',
            'One active state; StateMachine::fire() moves it. Generated ' + ctx.stamp + '.'
        ]) + '\n' +
`#pragma once
#include <string>

namespace sm {

enum class State : int {
${stateEnum}
    Count
};

enum class Trigger : int {
${trigEnum}
};

const char* to_string(State s);

class StateMachine {
public:
    StateMachine();              // constructs in the start state
    void  reset();               // return to the start state
    State current() const;       // the single active state
    bool  isFinal() const;       // current state is an end state

    // Fire a trigger. Returns true if a transition fired, false if the
    // trigger is not wired out of the current state (a harmless no-op).
    bool fire(Trigger t);
    bool fire(int trigger_id);   // integer overload

${perTrigger}

protected:
    // Called whenever the machine ENTERS a state (including reset()).
    // Override in a subclass to run state-specific logic.
    virtual void onEnter(State /*s*/) {}

private:
    State current_;
    void enter(State s);         // set + fire onEnter
};

} // namespace sm
`;
    }

    /* ── source ───────────────────────────────────────────────────── */

    function _emitSource(ctx, pattern) {
        const names = ctx.states
            .map(s => '        case State::' + s.cppEnum + ': return "' + _esc(s.name) + '";')
            .join('\n');
        const finalArm = ctx.finals.length
            ? ctx.finals.map(s => '        case State::' + s.cppEnum + ': return true;').join('\n')
            : '        // no end states';
        const perTrigger = ctx.triggers.length
            ? ctx.triggers.map(t =>
                'bool StateMachine::' + t.fnName + '() { return fire(Trigger::' + t.cppEnum + '); }'
              ).join('\n')
            : '// (no per-trigger helpers)';

        const dispatch =
            pattern === 'switch' ? _switchDispatch(ctx) :
            pattern === 'oop'    ? _oopDispatch(ctx) :
                                   _tableDispatch(ctx);
        const extraIncludes =
            pattern === 'oop'    ? '#include <array>\n#include <functional>\n#include <optional>\n' :
            pattern === 'table'  ? '#include <array>\n' : '';

        return emit.banner('state_machine.cpp  —  ' + ctx.ir.name, [
            'FSM implementation (' + pattern + ' dispatch). Generated ' + ctx.stamp + '.'
        ]) + '\n\n' +
`#include "state_machine.hpp"
${extraIncludes}
namespace sm {

const char* to_string(State s) {
    switch (s) {
${names}
        default: return "(invalid)";
    }
}

static const State kStart = State::${ctx.start.cppEnum};

StateMachine::StateMachine() { reset(); }

void StateMachine::reset() { current_ = kStart; onEnter(current_); }

State StateMachine::current() const { return current_; }

bool StateMachine::isFinal() const {
    switch (current_) {
${finalArm}
        default: return false;
    }
}

void StateMachine::enter(State s) { current_ = s; onEnter(current_); }

${dispatch}

bool StateMachine::fire(int trigger_id) {
    return fire(static_cast<Trigger>(trigger_id));
}

${perTrigger}

} // namespace sm
`;
    }

    function _tableDispatch(ctx) {
        const rows = ctx.fireable.length
            ? ctx.fireable.map(t =>
                '    { State::' + emit.pad(t.from.cppEnum + ',', 16) +
                'Trigger::' + emit.pad(t.trigger.cppEnum + ',', 16) +
                'State::' + t.to.cppEnum + ' },'
              ).join('\n')
            : '    // (no triggered transitions)';
        return `namespace {
struct Transition { State from; Trigger trigger; State to; };
constexpr std::array<Transition, ${ctx.fireable.length}> kTable = {{
${rows}
}};
} // anonymous namespace

bool StateMachine::fire(Trigger t) {
    for (const auto& tr : kTable) {
        if (tr.from == current_ && tr.trigger == t) {
            enter(tr.to);
            return true;
        }
    }
    return false;
}`;
    }

    function _switchDispatch(ctx) {
        const byFrom = new Map();
        ctx.fireable.forEach(t => {
            if (!byFrom.has(t.from.cppEnum)) byFrom.set(t.from.cppEnum, []);
            byFrom.get(t.from.cppEnum).push(t);
        });
        let cases = '';
        byFrom.forEach((list, fromEnum) => {
            const inner = list.map(t =>
                '            case Trigger::' + t.trigger.cppEnum + ': enter(State::' + t.to.cppEnum +
                '); return true;'
            ).join('\n');
            cases +=
`        case State::${fromEnum}:
            switch (t) {
${inner}
                default: break;
            }
            break;
`;
        });
        if (!cases) cases = '        // (no triggered transitions)\n';
        return `bool StateMachine::fire(Trigger t) {
    switch (current_) {
${cases}        default: break;
    }
    return false;
}`;
    }

    function _oopDispatch(ctx) {
        // Each state owns a handler: Trigger -> next State (or no move).
        // Stored in an array indexed by state — object-flavoured dispatch.
        const handlers = ctx.states.map(s => {
            const outs = ctx.fireable.filter(t => t.from.cppEnum === s.cppEnum);
            const arms = outs.map(t =>
                '            if (t == Trigger::' + t.trigger.cppEnum + ') return State::' + t.to.cppEnum + ';'
            ).join('\n');
            return `    handlers_[idx(State::${s.cppEnum})] = [](Trigger t) -> std::optional<State> {
${arms || '            (void)t;'}
        return std::nullopt;   // trigger not handled here
    };`;
        }).join('\n');

        return `namespace {
constexpr std::size_t idx(State s) { return static_cast<std::size_t>(s); }
using Handler = std::function<std::optional<State>(Trigger)>;
std::array<Handler, static_cast<std::size_t>(State::Count)> handlers_;
bool handlers_ready = false;

void build_handlers() {
${handlers}
    handlers_ready = true;
}
} // anonymous namespace

bool StateMachine::fire(Trigger t) {
    if (!handlers_ready) build_handlers();
    auto& h = handlers_[idx(current_)];
    if (!h) return false;
    auto next = h(t);
    if (!next) return false;
    enter(*next);
    return true;
}`;
    }

    /* ── demo main ────────────────────────────────────────────────── */

    function _emitMain(ctx) {
        const fireSeq = ctx.triggers.length
            ? ctx.triggers.map(t =>
`    std::cout << "fire " << "${_esc(t.name)}" << " : ";
    m.${t.fnName}();
    std::cout << "now in " << sm::to_string(m.current()) << "\\n";`
              ).join('\n')
            : '    std::cout << "(no triggers to fire)\\n";';

        return emit.banner('main.cpp  —  ' + ctx.ir.name + ' demo', [
            'Runnable smoke demo; subclass prints on each state entry.',
            'Build: make demo. Generated ' + ctx.stamp + '.'
        ]) + '\n\n' +
`#include "state_machine.hpp"
#include <iostream>

// Demo subclass: print whenever we enter a state.
class Demo : public sm::StateMachine {
protected:
    void onEnter(sm::State s) override {
        std::cout << "  entered " << sm::to_string(s) << "\\n";
    }
};

int main() {
    Demo m;
    std::cout << "start state: " << sm::to_string(m.current()) << "\\n";
    std::cout << "---- firing every trigger once ----\\n";
${fireSeq}
    std::cout << "final? " << (m.isFinal() ? "yes" : "no") << "\\n";
    return 0;
}
`;
    }

    /* ── GoogleTest ───────────────────────────────────────────────── */

    function _emitTests(ctx) {
        const cases = [];

        cases.push({
            name: 'StartsInStartState',
            body: 'sm::StateMachine m;\nEXPECT_EQ(sm::State::' + ctx.start.cppEnum + ', m.current());'
        });

        const fromStart = ctx.fireable.find(t => t.from.cppEnum === ctx.start.cppEnum);
        if (fromStart) {
            cases.push({
                name: 'FireFromStartMovesState',
                body:
`sm::StateMachine m;
bool moved = m.fire(sm::Trigger::${fromStart.trigger.cppEnum});
EXPECT_TRUE(moved);
EXPECT_EQ(sm::State::${fromStart.to.cppEnum}, m.current());`
            });
        }

        cases.push({
            name: 'UnknownTriggerIsIgnored',
            body:
`sm::StateMachine m;
sm::State before = m.current();
bool moved = m.fire(-1);   // integer overload: no such trigger
EXPECT_FALSE(moved);
EXPECT_EQ(before, m.current());`
        });

        cases.push({
            name: 'TODO_AddYourOwn',
            body:
`// Drive the machine and assert the resulting state, e.g.:
//   sm::StateMachine m;
//   m.fire(sm::Trigger::Something);
//   EXPECT_EQ(sm::State::Expected, m.current());
SUCCEED();`
        });

        return gen_tests.gtest({
            title: ctx.ir.name,
            header: 'state_machine.hpp',
            suite: 'StateMachineTest',
            cases
        });
    }

    /* ── Makefile ─────────────────────────────────────────────────── */

    function _emitMakefile(ctx) {
        return `# Makefile — ${ctx.ir.name} (FSM, C++)
# Generated by Machine Studio ${ctx.stamp}.

CXX      ?= c++
CXXFLAGS ?= -std=c++17 -Wall -Wextra -O2

all: demo

demo: state_machine.cpp main.cpp
\t$(CXX) $(CXXFLAGS) -o demo state_machine.cpp main.cpp

# GoogleTest: install libgtest-dev (or point at your own build).
# Links the gtest + gtest_main libraries.
test: state_machine.cpp test_state_machine.cpp
\t$(CXX) $(CXXFLAGS) -o run_tests state_machine.cpp test_state_machine.cpp -lgtest -lgtest_main -pthread
\t./run_tests

clean:
\trm -f demo run_tests

.PHONY: all test clean
`;
    }

    /* ── README ───────────────────────────────────────────────────── */

    function _emitReadme(ctx, pattern) {
        const triggerList = ctx.triggers.length
            ? ctx.triggers.map(t => '- `Trigger::' + t.cppEnum + '` / `' + t.fnName + '()` — ' + t.name).join('\n')
            : '_None._';
        const droppedNote = ctx.dropped > 0
            ? '\n> ⚠️ ' + ctx.dropped + ' transition(s) without a trigger were omitted.\n'
            : '';
        return `# ${ctx.ir.name} — Finite-State Machine (C++)

Generated by **Machine Studio** ${ctx.stamp} · \`${pattern}\` dispatch.

One state is active at a time. \`StateMachine::fire(Trigger)\` moves to the
target state for *(current, trigger)* if one exists (returning \`true\`) and
calls the \`onEnter\` hook; otherwise it is a no-op returning \`false\`.
${droppedNote}
## API (\`state_machine.hpp\`)

\`\`\`cpp
sm::StateMachine m;            // constructs in ${ctx.start.cppEnum}
m.reset();                     // back to the start state
sm::State s = m.current();     // active state
bool done  = m.isFinal();      // current is an end state?
bool moved = m.fire(sm::Trigger::Something);
\`\`\`

Subclass and override \`onEnter(State)\` for state-entry logic (see \`main.cpp\`).

### Triggers
${triggerList}

## Build & run

\`\`\`sh
make demo && ./demo
\`\`\`

## Tests (GoogleTest)

\`test_state_machine.cpp\` is a [GoogleTest](https://github.com/google/googletest)
template. With \`libgtest-dev\` installed:

\`\`\`sh
make test
\`\`\`

Cases cover the start state, the first transition out of it, and that an
unknown trigger is ignored — extend with your own scenarios.
`;
    }

    function _esc(s) { return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"'); }

    return { generate, SUPPORTED_PATTERNS };
})();

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { cpp_fsm };
}
