/**
 * generators/common/gen_tests.js
 * Machine Studio [MS] — test-file builders for generated code.
 *
 * The language generators (C / C++) build a small spec of test cases
 * from the IR, then hand it here to be wrapped in the right unit-test
 * framework:
 *   · C   → Unity   (setUp/tearDown + RUN_TEST in main)
 *   · C++ → GoogleTest (TEST() blocks, gtest_main provides main)
 *
 * These are deliberately framework-thin: the cases are passed in as
 * already-written assertion bodies so this module only owns the
 * scaffolding. The output is a runnable template — the user drops in
 * Unity / GoogleTest and builds the provided `test` target.
 *
 * Public:
 *   gen_tests.unity({ title, header, stubs, cases })  → C source
 *   gen_tests.gtest({ title, header, suite, cases })  → C++ source
 *
 * Where:
 *   stubs  : ['state_a', ...]  empty handler defs so the test links
 *            without main.c (C only)
 *   cases  : [{ name, body }]  name = test fn / TEST name,
 *            body = framework assertion lines (already indented 0)
 *
 * Depends on: emit.js
 */

const gen_tests = (() => {

    function _stamp() { return new Date().toISOString().slice(0, 10); }

    /* ── Unity (C) ────────────────────────────────────────────────── */

    function unity(spec) {
        const header = spec.header || 'state_machine.h';
        const stubs  = (spec.stubs || [])
            .map(fn => 'void ' + fn + '(void) { /* test stub */ }')
            .join('\n');

        const caseFns = (spec.cases || []).map(c =>
            'static void ' + c.name + '(void) {\n' +
            emit.indent(c.body, 4) + '\n}'
        ).join('\n\n');

        const runLines = (spec.cases || [])
            .map(c => '    RUN_TEST(' + c.name + ');')
            .join('\n');

        return emit.banner('test_state_machine.c  —  ' + (spec.title || 'tests'), [
            'Unity unit tests (template) — generated by Machine Studio.',
            'Build with the "test" target in the Makefile after dropping',
            'Unity (unity.c / unity.h / unity_internals.h) beside these files:',
            '    https://github.com/ThrowTheSwitch/Unity',
            'Generated ' + _stamp() + '. Safe to edit — add your own cases.'
        ]) + '\n\n' +
`#include "unity.h"
#include "${header}"

/* ── handler stubs ──────────────────────────────────────────────────
   The transition engine calls a per-state entry hook. The test build
   does not link main.c, so we provide empty definitions here. Replace
   with assertions on side effects if you wish. */
${stubs || '/* (no state handlers to stub) */'}

void setUp(void)    { sm_init(); }   /* fresh machine before each test */
void tearDown(void) { }

${caseFns}

int main(void) {
    UNITY_BEGIN();
${runLines}
    return UNITY_END();
}
`;
    }

    /* ── GoogleTest (C++) ─────────────────────────────────────────── */

    function gtest(spec) {
        const header = spec.header || 'state_machine.hpp';
        const suite  = spec.suite  || 'StateMachineTest';

        const testBlocks = (spec.cases || []).map(c =>
            'TEST(' + suite + ', ' + c.name + ') {\n' +
            emit.indent(c.body, 4) + '\n}'
        ).join('\n\n');

        return emit.banner('test_state_machine.cpp  —  ' + (spec.title || 'tests'), [
            'GoogleTest unit tests (template) — generated by Machine Studio.',
            'Build with the "test" target in the Makefile (links -lgtest',
            '-lgtest_main -pthread), or drop into your own CMake/CTest setup:',
            '    https://github.com/google/googletest',
            'Generated ' + _stamp() + '. Safe to edit — add your own cases.'
        ]) + '\n\n' +
`#include <gtest/gtest.h>
#include "${header}"

${testBlocks}

/* main() is provided by -lgtest_main. */
`;
    }

    return { unity, gtest };
})();

/* Node/headless export for the test harness. */
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { gen_tests };
}
